package animal;

import java.util.Random;

public class NameGenerator {

	// Array for names
	private String[] petName = { "BRISCO", "OFELIA", "POCHOMIL", "NALAA", "KI", "SOCRATE", "ORRY", "JEROMEY", "FLOPY",
			"DZEKO", "JJYODAA", "CHACHKA", "MACIE", "BANGA", "ANAKIN", "PATTON", "PAULIE", "MASH", "REENIE", "EWOK",
			"JULI", "HANSEL", "BYRON", "ANTOINE", "LEYLINES", "MAKAYLA", "PUGSLEY", "GIZZMO", "CRISTINA", "RYO-OHKI",
			"FRANCHI", "PACEY", "POTCHIE", "LONDYN", "CORALINE", "TAINA", "LANUDO", "TEARS", "BRANDY", "PUMBAA",
			"FOXIE", "WHEATIE", "PUP", "RINTON", "DIDDY", "ROOFUS", "MORDRID", "ZOMBOARD", "IGUAZU", "DUPPIE", "IUS",
			"HEINRICH", "ARK", "KOLBY", "BABUSHKA", "ODA", "NEI", "CLASH", "FIRBY", "PLISSKEN", "MINKA", "RAIDEN",
			"ALBA", "KRUZ", "MINNESOTA", "ANRIR", "EDGE", "MAXAMILLIAN", "PIERPONT", "REINER", "NEWTON", "CALEDONIA",
			"SAILOR", "BUFF", "PUCHY", "SHIEVA", "MICA", "JADE", "ROMRO", "ITSSY", "COUSCOUS", "PAC-MAN", "ETIENNE",
			"BOGS", "MOCALATTA", "PRIMO", "SASJA", "HERMES", "ARMANI", "HOJO", "THEODORA", "CHUCHO", "FIERCE", "WILSON",
			"IT'S", "CAPELLA", "SOSO", "LOURDES", "LASSY", "SUNNIE", "TEA", "GRESLY", "SWAN", "CHIKA", "SCHATZI",
			"SAVANNA", "HANA", "LARK", "FRISKET", "REKA", "LACEE", "TAPEY", "HARLEE", "SKYLARE", "PONCHIK)", "HATHAWAY",
			"BRADY", "STICKERS", "BUSTA", "CADDIE", "NUVE", "TRUBBLE", "POCHO", "POLLY-JANE", "HYENNA", "JENNIFER",
			"GRIFO", "NANAKI", "PORCUPINE", "NORFOLK", "SHINY", "ZAR", "CHIKI", "RUPERT", "MILIE", "SHAGGY'S", "NELA",
			"PULGA", "BLINKIN", "PANTHER", "BROOKLYN", "DILL", "CANELLA", "SEASAME", "MEDEA", "BREEZIE", "DUFFEY",
			"SANSA", "BUCKY", "ARYA", "BIJLI", "CARDELIA", "CHORKIE", "BOGEY", "SEABORN", "BANJOH", "SHA", "INCA",
			"TRAUBLE", "PAPITO", "GOJI", "MAHOGANY", "BISON", "DANNI", "KLEOPA", "TY", "MACNULTY", "SANGA", "GEYA",
			"JACQUES", "MESSIAH", "DIWALI", "BABBU", "WARDEN", "MOORLAND", "CARMELINA", "JERICHO", "TILLIE-TIFFANY",
			"YOM", "SEVERUS", "LAINEY", "KUNO", "WILLOUGHBY", "GODRIC", "MUSKETT", "LENORE", "FLOSSIE", "FLUFFYMATT",
			"BAGELS", "MAURIE", "JUMBO", "EMILEO", "OAKLEY", "NANDI", "MS.SCRUFFY", "MATCH", "ZACKIA", "HERMAN,",
			"PLAYA", "GARLIC", "MICHAELANGELO", "COMPASS", "BROWSER", "PANCAKES", "TREVI", "JETHEO", "BLOSSUM",
			"PAMELA", "BROOKYN", "BLEACH", "DAFFNEY", "AALIYAH", "GIA", "SYDNEY", "WHIMSEY", "ROUXIE", "TRALFAZ",
			"SHEILA", "CORDELIA", "MUSCLES", "EARTHA", "HOKEE", "OCEAN", "GRIMLOCK", "GG", "BROOMSTICKS", "CHIGURH",
			"ATHEWA", "TERRIER", "MAISY", "ALEJANDRO", "DUBI", "HASHBROWN", "PAULEY", "ESSESS", "SENOR", "NANUQ",
			"BERTHA", "CHOPPA", "SWEETIE", "ZLATAN", "BREEZA", "BOOWOO", "MAURICO", "VLA", "PIPSQUEEK", "BRUTTO",
			"OULYMATA", "YULIE", "SERPICO", "MILO.", "DIANNA", "WHITEY", "SALSA", "ELOIS", "KELLIE", "RAMZI", "GNARLY",
			"ALIX", "TORONTO", "ELROY", "MERYL", "BULGARI", "PEARLLY", "CONWAY", "PHEEBEE", "ICHIGO", "BIFF", "BREANNA",
			"INEZ", "MILOU", "KAIOUS", "SHEERA", "ISIDORA", "MILKYWAY", "JINGLE", "ZOIIE", "TOOTHIE", "PUZZLE",
			"QUARTZ", "FUKU", "ALFIE", "TRUFFLE", "HIKARI", "BRONZE", "PERLA3", "PATTYLOU", "DECOY", "PARSIFAL",
			"DARTACAN", "LOBO", "SQUISHEE", "HAPPY", "DIZO", "OTIE", "KOUKLA", "DIPSEA", "NUCELLA", "CHUMLEY", "BARTEK",
			"TEMPURA", "TRUCKDOGG", "FARVA", "BLUFF", "NIXXIE", "ANNIELEIGH", "CHYNNA", "GEMMI", "PAJAMA", "EDGIE",
			"CARLO", "SOUL", "KERO", "KELBY", "TAMMI", "POPS", "WIZARD", "KEYLA", "BRUSSELS", "THE", "BRANDON", "PAULA",
			"CAMEN", "BRENDALL", "LEEZA", "SHAYLEE", "PRINCE`", "TORCH", "WU", "MATTIE", "BORACHO", "RANDOLF", "DECLAN",
			"SYMPHONY", "FATBOY", "PINYA", "KOUFAX", "CELBEN", "CHUWI", "FRO", "KUZ'MA", "HILLARY", "DIGSBY", "TARAN",
			"CUNON", "AMADEUS", "LEFTY", "QUAVO", "EARNEST", "JOST", "INDIE", "YAYLEY", "MORUS", "ROO", "BRADLEIGH",
			"JOLIN", "INGA", "CHACHA", "TRAFFIC", "PEBBLES", "GERDIE", "SHRIMPY", "MACK", "CAPI", "LEO-MILO", "KAMBO",
			"ISRAEL", "IAN", "HORANG", "JA", "COCOPUFF", "STINKY", "GARDA", "BUG-Z", "CUCKOO", "GARRATT", "LULLY",
			"REGGAE", "RAWLY", "BUDDYC", "KADEEN", "SHINOBI", "GUSTY", "DAPHNE", "MEAN", "RONIN", "CARMELITA",
			"RENFIELD", "BES", "MUSHROOM", "PERRY", "MACHETE", "JEDI", "ERNE", "CECILIA", "HAIDA", "BARRON", "CLAIRE",
			"GOUMBA", "SEVEN", "SAMIA", "BREEZY", "XEROX", "JONNY", "VICTORY", "CALLAN", "JAZZMINE", "ESTRELLA",
			"EXTRELLITA", "RIO", "TINKY", "TOOTSIES", "SHERMAN", "SAMSON", "ANAT", "KAZI", "FLY", "SUSSY", "SHOJI",
			"LAINA", "DOPPY", "MOOKI", "KELLER", "DANIELLA", "OUCHY", "CHI-INEZ", "TOPE", "DARWIN", "MICHELL", "AVENUE",
			"PISA", "SAMADHI", "SALAMANDER", "BURNY", "SHANDY", "PATRICIA", "MILK", "NUSCH", "HEADY", "REDFORD", "AR",
			"JR.", "KALONA", "GULASH", "TIGO", "EUGENE", "ZEPPOLE", "SCHULTZY", "SARGEANT", "COLTRANE", "MARTHA",
			"CAMIIA", "BAMBA", "FLAN", "FUSS", "LUCERNE", "SHAYNA", "BOWZER", "JACKA", "SUMMIT", "MAXIK", "EDUARDO",
			"HOWDY", "MEGGY", "LION", "REZ", "CHESTON", "DASEIN", "JAYME", "ROXI", "CHASE-CASTLE", "UTAH", "CEDRICK",
			"TIMBO", "MUSHOO", "WHOOPIE", "ROSALIND", "SIGFREID", "CHEETO", "CHUMLEE", "POCHACCO", "ARIE", "PARADISE",
			"ROBBEE", "CRICKET", "SOLEIL", "PHANTOM'S", "LIFFEY", "SARAH", "SILVIE", "PASQUALEE", "GOLDENDOODLE", "LUA",
			"CELY", "MERCURY", "GRAE", "ADELLA", "JUDO", "PJOTR", "KAYLIAH", "MYSTIQUE", "SABINA", "SISLO", "NOODLES",
			"SATTA", "SCOOB", "KAPRIZ", "PATINA", "TURNIP", "SQUEAKY", "MIOO", "CJ1", "JAMISON", "RISA", "NOMI", "OSLO",
			"DIPPY", "CHARM", "FOFFY", "PEQUENITA", "ODEE", "SOTHIS", "SCOSKY", "YANA", "FLUFFITO", "PHENIX", "DENNY",
			"YASMIN", "RENEGADE", "CYNDIA", "DIPP", "OLAF", "HOOZIE", "BELARUS", "BROOKLIN", "SAFARIE", "SPIKERTON",
			"MOCHT", "ARAYA", "SASCHIE", "ZEENA", "MERQUJUQ", "GIGIO", "VERNY", "VITUS", "STARDIVINA", "MASTERSHAKE",
			"MOXLEY", "BUGGA", "CANVAS", "LUCUS", "SAPO", "LOMI", "QUEENS", "ZUKI", "AXEL", "DOC", "SIR.", "HOPPY",
			"TRIXX", "SHOO", "KALI", "APALLO", "DUDELY", "HOBBY", "PERRITO", "DINGDING", "BABEE", "CEE", "HERMIONE",
			"BANG", "FENDI", "CESAR", "ALLEY", "POSEIDON", "AMICA", "NEMBU", "LALIBELA", "MAITAI", "ICESIS", "NEGRETA",
			"ZENCHI", "SKY-LA", "MATEO", "HOSS", "JOSEPHUS", "BAZI", "LU-LU", "KAYCEE", "ULI", "ARTY", "BEHR", "TOPSY",
			"C.D.", "SUSU", "KODIE", "KENSEY", "JENNIE", "GOZER", "DROGBA", "LESLEY", "NIGEL", "MITTIZZI", "SMOOCHIE",
			"HOUSTON", "MCPHERSON", "WALICE", "ARMSTRONG", "HEISMAN", "CALEY", "PICCO", "FOTCH", "SCARLETT",
			"BLANKYPOTY", "TEANNA", "LILO", "SEINFELD", "NORTH", "LEGION", "COCOBELLA", "MARCI", "BABBY", "RAIN",
			"HYBRID", "CAS", "LION-O", "JEIRA", "TILA", "CHEE", "TANANA", "SKUNKY", "GORDY", "CAVALIER", "JANUARY",
			"MILTA", "TALULAH", "XAVIER", "PD", "FREIDA", "BLARNEY", "RABBY", "GINGERSPCE", "ELZY", "CRIP", "ELIDIN",
			"ZEPHYR", "ZORRO", "ROBY", "MISTYESE", "BOT", "BAMBOU", "SILIA", "MATADOR", "GINGERBREA", "FENNY", "ZANDER",
			"TIAMAT", "SHUMI", "DISCOVERY", "JEAN", "LULA", "JOKER", "BOONIE", "ADELE", "KANY", "JUSTICES", "SAPHIRA",
			"GABRIELA", "POOKAH", "TYGA", "GHOULIE", "JONH", "CHIQUITIN", "SHLOMO", "PHISH", "AIDEN", "BENNO", "BEEBEE",
			"SACHA", "TOLLIVER", "MICK", "CONA", "FRANJO2", "VITO", "KORA", "BABALU", "DJANGO", "MUNECO", "MEISHI",
			"JEAN-CLAUDE", "LINDA", "KOKEE", "WING", "RAGNAROK", "SIRRIE", "DAIZY", "GEOFFREY", "DELIA", "MAXWEL",
			"BRIDGET", "BROOKE", "PULLO", "GROMET", "BEBIE", "KAHVE", "MIMI-LEANDRA", "PINPON", "IGGI", "TERRIANN",
			"MAMMA", "CHOCOLO", "SUEDE", "HORNET", "TASYA", "INIGO", "PIERO", "SKIMO", "ANEECE", "PARIS", "MOHAWK",
			"TAMY", "PIECES", "PEACH", "LADDIE", "BRYDIE", "DUNKEL", "GINNY", "FETCH", "WADE", "TYNI", "IDLI", "BENGAL",
			"MACY", "LISKER", "CAULFIELD", "DE'NIRO", "ROBBIN", "ODYSSEY", "MAROR", "BLUE-BELLE", "THELONIOUS", "RIKKY",
			"CLOWE", "CHEESEBURGER", "GLENDALINE", "MALISH", "SHAZZIE", "TICTAC", "RANGER", "SAVANNAH", "LELENE",
			"TADPOLE", "BAILEYM", "COOHIE", "DAZLLE", "MORDECAI", "CHUBZ", "CUTE", "QUEENEY", "BAILYEE", "ECHO", "BEX",
			"MURIEL", "TASA", "ELIE", "SAKI", "NEMA", "SWISSY", "ZIBBY", "GLADSTONE", "MONIS", "HYDE", "MAFALDA",
			"MOTZART", "NINASIMONE", "WILFRED", "BISKY", "TROT", "ALABAMA", "MOLLYBEAR", "BRENDAL", "STARBUCK",
			"GIULIANI", "THURBER", "ARIES", "HEFFIE", "ABRIK", "JULIEN", "NISA", "NAIKA", "DUQUE", "CHUEY", "HAZE",
			"GWEENIE", "ISSAC", "CHAVO", "MAKS", "BODEN", "ARLO", "FERGIE", "SID", "ESCO", "KEWBIE", "TAMARA", "CHONG",
			"HAPOOH", "TRINKET", "SUTTER", "PLAZI", "FRAISER", "LEE-O", "XÖE", "POPCORN-MINTO-JACK", "ZELDA", "ZORI",
			"JITS", "BOOJUM", "GONZO", "JIGGETTS", "MIMMIE", "THORR", "CERVARIS", "LOLAJEAN", "MUCCA", "OXLEY",
			"DAVIDSON", "NAN", "TIGER", "DANKE", "FRAZIER", "MANGO", "CAL", "CORKIE", "LUI", "ELLA", "EZEKIEL", "LEEGO",
			"DALI", "BRIAR", "MARLOWE", "GREG", "GIOVANNA", "D-LU", "ROBINS", "GORDA", "MELODIE", "NORAH", "CHICA-BEL",
			"JILLIAN", "FATSO", "HAYLEIGH", "THUMBALINA", "CARERRA", "VIRGINIA", "SKYPE", "PERSON", "CAPTAUN",
			"BRUNELLO", "SIROB", "JOOJOO", "BEEMKA", "TATOU", "CHICHO", "SKYLA", "BAABAA", "BISCUIT", "PINEAPPLE",
			"TONNE", "STAN", "LAZARUZ", "FRANCIE", "GURGI", "MEHOW", "BLAZIN", "TUBA", "SIKU", "KAIDO", "ZHUCHKA",
			"MICHY", "R.", "GAVIN", "BADOOK", "CHORONG", "LILLIBELLE", "MAYDAY", "SURYA", "VLADIMIR", "FRITO",
			"KUROSAKI", "DEROSA", "MARLIN", "PUZZUNO", "MAKENA", "GRUMPY", "BENO", "KARISMA", "ANDERS", "SHEIBA",
			"WILL", "GRAINNE", "SALVADOR", "KLEINE", "RICK", "DINDIN", "ZABAR", "ZEPPELIN", "SOL", "HUBERT", "ME",
			"SOPHEA", "KAYA", "KASCHEU", "HENLEY", "MARZIPAN", "MUÑECA", "PEP", "ANYA", "BELLADONA", "COUDY", "GAMBIT",
			"WOLFGANG", "UMKNOWN", "TYPHON", "DUM", "JULIE", "ESTEVE", "ANNECY", "RAFEE", "SLIPPERS", "GERI",
			"CHESTERFIELD", "NATILDE", "RAMSEY", "LOUSTIC", "BOURLOUKO", "NUPY", "MARYLIN", "PRINCES", "GREYNI",
			"NAILA", "ZHEKA", "LITT", "BOSTON", "TEO", "FRANCO", "DARCY", "REECES", "PRESCIOUS", "KIMMIE", "GOLDIE",
			"BOBEK", "CHAKIE", "SCHOTTZIE", "KYLA", "HEATHROW", "FRIGGIT", "ZENAFINA", "BUNS", "CHIANTI", "MOONSHINE",
			"HERA", "PANDAK", "WOOFIE", "SUGIHARA", "KASE", "LETHO", "SPOON", "BAMBO", "CLOUD", "ZUTY", "LEONIDIS",
			"PIRULINA", "FANG", "KEEYO", "TORRI", "FROSTY", "LUELLA", "PAM", "TOBEE", "CONSTANCE", "SENSI", "URI",
			"KAHLO", "TUCI", "SHAUHNA", "FEBO", "TASHA", "CUSHI", "ZAEKA", "MONA", "POTTER", "DIANA", "VIOLA", "BUPKIS",
			"IWA", "ALKA-ALI", "ROLO", "RABIES", "TARA", "YAEGAR", };

	public NameGenerator() {
		// TODO Auto-generated constructor stub
	}

	public String getRandomName() {
		// return a random name

		Random r = new Random();

		// pick a petname and surname based on length of array
		String name = petName[r.nextInt(petName.length)];

		return (name);

	}

}
